### ISSUE TITLE
JSONDecodeError("Expecting value", s, err.value)

### ISSUE THREAD

**Issue by atowersc** [lit26/finvizfinance#13]
I am getting this error when I try to execute the performance function of the Future class

```
from finvizfinance import future

def perform():

    fut = future.Future()
    fut.performance(timeframe="W")

perform()
```

this is what i get

`Traceback (most recent call last):
  File "/home/TBot/table.py", line 9, in <module>
    perform()
  File "/home/TBot/table.py", line 7, in perform
    fut.performance(timeframe="W")
File "/home/TBot/env/lib/python3.7/site-packages/finvizfinance/future.py", line 49, in performance
    data = json.loads(data.strip()[:-1])
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I would also like to add that it would be convenient to have a quote function for each of the indices. I've been looking a bit and I think it's not implemented.

**Comment by lit26** [comment]
I think finviz removed the table on their website. So this will be removed from my library. I will try to get this information back in the future.
