### ISSUE TITLE
Persistant bug related to night mode

### ISSUE THREAD

**Issue by jobidon** [lit26/finvizfinance#75]
The fix for issue #73 is apparently not complete
```
pip list|grep finvizfinance
finvizfinance       0.14.6rc1
```
and when calling the `finvizfinance(ticker=ticker).ticker_fundament()` function, I get an error in the exception handler:
```Traceback (most recent call last):
  File "/home/eric/.local/lib/python3.11/site-packages/finvizfinance/quote.py", line 142, in ticker_fundament
    ) = rows[2].text.split(" | ")
        ~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/dev/polygon/yahoo.py", line 95, in <module>
    analyzeStock("MRVL")
  File "/home/eric/dev/polygon/yahoo.py", line 65, in analyzeStock
    quote=finvizfinance(ticker=ticker).ticker_fundament()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric/.local/lib/python3.11/site-packages/finvizfinance/quote.py", line 145, in ticker_fundament
    (_, fundament_info["Company"], _) = rows[0].text.split(' | ')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)
```
Adding a trace on `print (rows[1].text)` and `print (rows[2].text)` prints this: 
```
Technology | Semiconductors | USA | NASD
Cannot parse Company, Sector, Industry and Country
```

**Comment by lit26** [comment]
Can you test the PR? Maybe they change something.

**Comment by nicklasti** [comment]
Hi, I'm also having the error
